name: Deploy

on: push

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run migrations:migrate
        env:
          DB_URL: ${{secrets.DB_URL}}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "andre-staart-deploy"
          heroku_email: ${{secrets.HEROKU_USER_EMAIL}}
  development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run migrations:migrate
        env:
          DB_URL: ${{secrets.DB_URL}}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "andre-staart-deploy"
          heroku_email: ${{secrets.HEROKU_USER_EMAIL}}
